/**
 * Database types for Supabase
 * This file will be auto-generated by: supabase gen types typescript --local
 * Placeholder for now - replace with generated types after Supabase setup
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string | null;
          display_name: string | null;
          preferred_translation: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          username?: string | null;
          display_name?: string | null;
          preferred_translation?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          username?: string | null;
          display_name?: string | null;
          preferred_translation?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      sermon_notes: {
        Row: {
          id: string;
          user_id: string;
          passage_reference: string;
          sermon_title: string | null;
          sermon_date: string | null;
          generated_outline: Json | null;
          user_notes: string | null;
          reflection_answers: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          passage_reference: string;
          sermon_title?: string | null;
          sermon_date?: string | null;
          generated_outline?: Json | null;
          user_notes?: string | null;
          reflection_answers?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          passage_reference?: string;
          sermon_title?: string | null;
          sermon_date?: string | null;
          generated_outline?: Json | null;
          user_notes?: string | null;
          reflection_answers?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
}
