/**
 * Database types for Supabase
 * This file will be auto-generated by: supabase gen types typescript --local
 * Placeholder for now - replace with generated types after Supabase setup
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string | null;
          display_name: string | null;
          preferred_translation: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          username?: string | null;
          display_name?: string | null;
          preferred_translation?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          username?: string | null;
          display_name?: string | null;
          preferred_translation?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      questions: {
        Row: {
          id: string;
          mode: string;
          difficulty: string;
          verse_reference: string;
          question_text: string;
          correct_answer: string;
          incorrect_answers: Json;
          strongs_number: string | null;
          explanation: string | null;
          verified: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          mode: string;
          difficulty: string;
          verse_reference: string;
          question_text: string;
          correct_answer: string;
          incorrect_answers?: Json;
          strongs_number?: string | null;
          explanation?: string | null;
          verified?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          mode?: string;
          difficulty?: string;
          verse_reference?: string;
          question_text?: string;
          correct_answer?: string;
          incorrect_answers?: Json;
          strongs_number?: string | null;
          explanation?: string | null;
          verified?: boolean;
          created_at?: string;
        };
      };
      game_progress: {
        Row: {
          id: string;
          user_id: string;
          mode: string;
          questions_answered: number;
          correct_answers: number;
          current_streak: number;
          best_streak: number;
          last_played_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          mode: string;
          questions_answered?: number;
          correct_answers?: number;
          current_streak?: number;
          best_streak?: number;
          last_played_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          mode?: string;
          questions_answered?: number;
          correct_answers?: number;
          current_streak?: number;
          best_streak?: number;
          last_played_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
}
