/**
 * Database types for Supabase
 * This file will be auto-generated by: supabase gen types typescript --local
 * Placeholder for now - replace with generated types after Supabase setup
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string | null;
          display_name: string | null;
          preferred_translation: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          username?: string | null;
          display_name?: string | null;
          preferred_translation?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          username?: string | null;
          display_name?: string | null;
          preferred_translation?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };

      strongs_entries: {
        Row: {
          number: string;
          language: string;
          lemma: string;
          transliteration: string;
          pronunciation: string | null;
          definition: string;
          part_of_speech: string | null;
          kjv_usage: Json | null;
          created_at: string;
        };
        Insert: {
          number: string;
          language: string;
          lemma: string;
          transliteration: string;
          pronunciation?: string | null;
          definition: string;
          part_of_speech?: string | null;
          kjv_usage?: Json | null;
          created_at?: string;
        };
        Update: {
          number?: string;
          language?: string;
          lemma?: string;
          transliteration?: string;
          pronunciation?: string | null;
          definition?: string;
          part_of_speech?: string | null;
          kjv_usage?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };

      sermon_notes: {
        Row: {
          id: string;
          user_id: string;
          passage_reference: string;
          sermon_title: string | null;
          sermon_date: string | null;
          generated_outline: Json | null;
          user_notes: string | null;
          reflection_answers: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          passage_reference: string;
          sermon_title?: string | null;
          sermon_date?: string | null;
          generated_outline?: Json | null;
          user_notes?: string | null;
          reflection_answers?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          passage_reference?: string;
          sermon_title?: string | null;
          sermon_date?: string | null;
          generated_outline?: Json | null;
          user_notes?: string | null;
          reflection_answers?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
